export { default } from "./axios"
export { default as jsonp } from "./jsonp"
export { default as gqlQuery } from "./gqlQuery"
export { default as uploadImage } from "./uploadImage"
export { default as code2token } from "./code2token"
export { default as getApiHost } from "./getApiHost"
export { default as getBaseUrl } from "./getBaseUrl"
export { default as uploadBase64Image } from "./uploadBase64Image"
export { default as restRequest } from "./restRequest"
